name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'Digger Specification'
        required: true
      run_name:
        description: 'Digger Run Name'
        required: false

run-name: '${{inputs.run_name}}'

jobs:
  digger-job:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: write
      pull-requests: write
      issues: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ fromJSON(github.event.inputs.spec).job_id }}
        run: echo "job id ${{ fromJSON(github.event.inputs.spec).job_id }}"

      - name: Run Digger
        uses: diggerhq/digger@vLatest
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          digger-spec: ${{ inputs.spec }}
          setup-terraform: true
